"""add pipeline_kind to pipeline_runs

Revision ID: 779af5521153
Revises: a2eaa148e044
Create Date: 2026-07-23 12:43:48.350547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779af5521153'
down_revision: Union[str, None] = 'a2eaa148e044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows to "analytics" so adding a NOT NULL
    # column to a non-empty table doesn't violate the constraint.
    op.add_column(
        'pipeline_runs',
        sa.Column('pipeline_kind', sa.String(length=50), nullable=False, server_default='analytics'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline_runs', 'pipeline_kind')
    # ### end Alembic commands ###
