"""add notification fields to users

Revision ID: 9cb171d67eae
Revises: 779af5521153
Create Date: 2026-07-23 22:39:18.800416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb171d67eae'
down_revision: Union[str, None] = '779af5521153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('last_reauth_notified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_reauth_notified_at')
    op.drop_column('users', 'notification_email')
    # ### end Alembic commands ###
